import React from 'react'


function About(){
    return (
        <div>
        <div><h1>About me</h1></div>
        <p> TLDR; Whether it's in the kitchen or an IDE, I am fueled by my passion for learning and creating. I bring with me an instinctual proficiency with Communication and Teamwork from food service and management. I am always hungry to learn. CURRENTLY LOOKING FOR ROLE IN PORTLAND, OR.</p>
        <p>I am a bootcamp graduate from PDX Code Guild in Portland, Or. My background is in the service industry working with food and customers and managing teams. I love learning new things and working into a lead position where I can use my experience to teach others and help them grow. I started working at Subway out of high school and couldn't cook anything that didn't come out of a box with instructions. Now I feel comfortable following any recipe or multitasking an entire dinner spread! I've come such a long way, but I never saw myself running my own resturant. I have learned so much from this industry and will forever be grateful, but it is time for me to move on and apply my growth to another field. The skills I love using at work include problem solving, organization, time management, and collaborating. I enjoy being able to layout a plan so when things go off the rails (because they will somehow), it is easy to revaluate and get back on track. I am inspired by that feeling of overcoming obstacles with my teammates. </p>
        <p> I have always dreamed of working in tech, but I grew up in a rural part of the country where I didn't actually know anyone in that field. I assumed that to become a professional programmer you had to be a super math genius. I didn't have any role-models for reference into what this industry is realistically like. I finally made it to city living a few years ago where I got to be exposed to more industries and ways of life. That's when I discovered coding bootcamps. This made continuing my education accessible! I worked hard for a couple of years and saved for the tuition, and now I am working harder to network in an effort to learn more about the industry. I am also doing my best to self teach on top of the foundation of technology I learned in the bootcamp. Trying to navigate that bootcamp limbo of finding the first job that will open up my future career has been daunting and discouraging, but it's only made me think more creatively about networking and ways to improving my portfolio. </p>
        <p>Outside of work, I enjoy games, cooking and the company of my pets. I am someone who truly appreciates the down time of being at home to recharge. I have spent way too many hours playing Animal Crossing this year. I enjoy table tops games with my fiance like Catan. My two cats are named after nerd culture references if you need any more proof that I'm a dork. I am also two years deep into a Dungeons and Dragons campaign with some friends. Helping the Dungeon Master transition to technologies like discord bots and dice rolling macros to make our meetups become remote has been one of the highlights of quarantine. haha. I love when the skills I have picked up professionally can also be beneficial at home. Another hobby of mine is a sort of mini menu pairing I like to create sometimes to experiment in the kitchen. I will find a starting point to be inspired by like a cocktail that sounds refreshing on a whim. Then I will deep dive into flavor profiles and put together a complete complimentary meal that I can cook for my partner or friends. They have been <i>mostly</i> successful. </p>
        <p>My github has been a little quiet recently, unfortunately. The reality is that the world is very different than it was a few months ago, and as an 'essential worker' during these recent months, I have been very careful to maintain a healthy balance for myself. However, I am still passionate about starting my career! If you made it this far and know of an entry level career opportunity or want to chat about cats or board games or kitchen blunders, please visit the CONTACT tab and reach out!</p>
        Stay safe. 
        -Tabatha
        </div>
    )}

export default About
